float getFloat(char[]);
int getInt(int*, char[], char[], int, int);
int utn_getNumero(int* pResultado, char* mensaje, char* mensajeError, int minimo, int maximo, int reintentos);
float add(float, float);
float subtract(float, float);
float divide(float, float);
float multiply(float, float);
long int factorial(float);
void pedirAlumno(int[], int[], char[], int[], int[], float[], int);
void mostrarUnAlumno(int, int, char, int, int, float);
void mostrarAlumnos(int[], int[], char[], int[], int[], float[], int);
void ordenarAlumnos(int[], int[], char[], int[], int[], float[], int);
void getNombreApellido(char[]);
